apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak in Kubernetes

type: application

version: 0.1.0
appVersion: 25.0.4

dependencies:
  - name: postgresql
    version: 14.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
