apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak in Kubernetes

type: application

version: 22.1.3
appVersion: 25.0.3

dependencies:
  - name: postgresql
    version: 14.13.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
