apiVersion: v2
name: keycloak
description: A Helm chart for deploying Keycloak in Kubernetes

type: application

version: 0.1.0
appVersion: 18.0.0

dependencies:
  - name: postgresql
    version: 12.1.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
