replicaCount: 1

image:
  repository: bitnami/keycloak
  tag: 18.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

postgresql:
  enabled: true
  auth:
    database: keycloak_db
    username: keycloak_user
    password: keycloak_password

# Aquí puedes añadir más configuraciones específicas para Keycloak
