apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-keycloak-postgresql-0
spec:
  capacity:
    storage: 8Gi  # Debe coincidir con lo que solicita la PVC
  accessModes:
    - ReadWriteOnce  # Debe coincidir con lo que solicita la PVC
  persistentVolumeReclaimPolicy: Retain  # O Delete, dependiendo de cómo quieras manejar la eliminación
  storageClassName: "local-path"  # Debe coincidir con lo que está especificado en el PVC o dejarlo en blanco si no se utiliza StorageClass
  hostPath:  # Usando hostPath si estás en un entorno local; para producción, usa algo más adecuado
    path: /mnt/data/keycloak-postgresql  # Este es el path en el nodo
  volumeMode: Filesystem  # Debe coincidir con lo que solicita la PVC
