replicaCount: 2

image:
  repository: bitnami/keycloak
  tag: 18.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

postgresql:
  initContainers:
    - name: fix-permissions
      image: busybox
      command: ["sh", "-c", "chown -R 1001:1001 /bitnami/postgresql"]
      volumeMounts:
        - name: data
          mountPath: /bitnami/postgresql
  enabled: true
  persistence:
    enabled: true
    storageClass: local-path
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    mountPath: /bitnami/postgresql
  securityContext:
    enabled: true
    runAsUser: 1001
    fsGroup: 1001
  auth:
    database: keycloak_db
    username: keycloak_user
    password: keycloak_password